- name: Publish the files to remote server
  uri:
    url: http://flaskapp.middlewareinventory.com
    method: POST
    headers:
      Content-Type: "multipart/form-data"
    src: '{{ item.path }}'
    status_code: 302
  register: publishcsv
  with_items:
    - '{{ filetocopy.files }}'
